version: '3.8'

services:
  neo4j:
    image: neo4j:community-bullseye
    container_name: fpf-graph-data
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    volumes:
      - /Users/eugene/Dev/ai-assistants/fpf-neo4j-data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_logs:
